In [1]:
print("2hi")

2hi


In [1]:
import numpy as np 

In [4]:
one_d_array = np.array([3,6,9])

In [5]:
one_d_array.ndim

1

In [6]:
one_d_array.size

3

In [7]:
one_d_array.shape

(3,)

In [41]:
two_d_array = np.array([[1,2,3],[4,5,6]])

In [12]:
two_d_array.ndim

2

In [13]:
two_d_array.size

6

In [14]:
two_d_array.shape

(2, 3)

In [15]:
l = [8, 12, 16, 24, 4]

In [18]:
sorted(l)

[4, 8, 12, 16, 24]

In [20]:
min(l)

4

In [21]:
sum(l)

64

In [22]:
64 / 5 

12.8

In [23]:
64 / 4 

16.0

In [29]:
l2 = [(score - 16)** 2 for score in l]

In [27]:
l2

[64, 16, 0, 64, 144]

In [30]:
sum(l2) / 4 

72.0

In [32]:
arr = np.array([1,2,3,4,5])

In [33]:
arr.max()

5

In [34]:
arr.min()

1

In [35]:
arr.mean()

3.0

In [48]:
two_d_arr = np.array([[3,6,9,6,11], [12,9,22,54,46]])

In [45]:
two_d_arr

array([[ 3,  6,  9,  6, 11],
       [12,  9, 22, 54, 46]])

In [49]:
np.sort(two_d_arr)

array([[ 3,  6,  6,  9, 11],
       [ 9, 12, 22, 46, 54]])

In [50]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [52]:
a = np.ones (3)

In [53]:
a 

array([1., 1., 1.])

In [54]:
np.empty(4)

array([-0.00000000e+000, -0.00000000e+000,  3.79027218e+179,
        2.82478432e-309])

In [60]:
l = [11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20]
l.sort()
l

[11, 11, 11, 12, 12, 13, 13, 14, 14, 15, 16, 17, 18, 19, 20]

In [65]:
np.unique(l)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [2]:
import pandas as pd